[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "shopifyscraper"
authors = [{name = "Aiden Smith", email = "aiden.smith24@protonmail.com"}]
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]
readme = "README.md"
